version: "3"
services:
  test_app:
    container_name: test_app
    environment:
      - REDIS_HOST=redis
      - DATABASE_HOST=postgres
      - BUNDLE_PATH=/vendor
    build:
      context: .
      args:
        - BUNDLE_PATH=/vendor
    volumes:
      - .:/app:cached
      - test_app-cache:/app/tmp/cache
    ports:
      - "9009:9009"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec unicorn -p 9009 -c config/unicorn.rb"
    tty: true
    stdin_open: true
    links:
      - postgres
      - redis
    networks:
      - my_local_dev_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "6499:5432"
    volumes:
      - test_app-postgres:/var/lib/postgresql/data
    networks:
      - my_local_dev_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - test_app-redis:/var/lib/redis/data
    networks:
      - my_local_dev_network

volumes:
  test_app-postgres:
  test_app-redis:
  test_app-cache:

networks:
  my_local_dev_network:
    name: my_local_dev_network